import { Item } from '../types';

const IGNORED_WORDS = [
  'subtotal',
  'total',
  'iva',
  'cuit',
  'fecha',
  'hora',
  'ticket',
  'factura',
  'mozo',
  'mesa',
  'gracias',
  'visita',
  'fiscal',
  'cambio',
  'efectivo',
  'tarjeta',
  'propina',
  'ingresos brutos',
  'i.v.a',
  'caja',
  'sucursal',
  'terminal',
  'operacion',
  'visa',
  'mastercard',
  'debito',
  'credito',
  'telefono',
  'tel:',
  'pago',
  'consumo',
  'descuento',
  'recargo',
  'importe',
  'cant',
  'descripcion',
  'p.unit',
  'precio'
];

/**
 * Normalizes number formats like "12.500,00", "12500.00", "12,500", "4500" into a standard JavaScript number
 */
export function parsePriceNumber(rawStr: string): number {
  let cleaned = rawStr.trim().replace(/[$sS§]/g, '').replace(/[\-_+=:;.]+$/, '').trim();

  // If format is like 12.500,00 or 1.250,50
  if (/^\d{1,3}(\.\d{3})+(,\d{1,2})?$/.test(cleaned)) {
    cleaned = cleaned.replace(/\./g, '').replace(',', '.');
  }
  // If format is like 12,500.00
  else if (/^\d{1,3}(,\d{3})+(\.\d{1,2})?$/.test(cleaned)) {
    cleaned = cleaned.replace(/,/g, '');
  }
  // If format is like 12500,50
  else if (/^\d+,\d{1,2}$/.test(cleaned)) {
    cleaned = cleaned.replace(',', '.');
  }
  // If format is like 12.500 (Argentine peso without decimals)
  else if (/^\d{1,3}\.\d{3}$/.test(cleaned)) {
    cleaned = cleaned.replace(/\./g, '');
  }
  // Plain numbers or standard decimals
  else {
    cleaned = cleaned.replace(/[^0-9.]/g, '');
  }

  const num = parseFloat(cleaned);
  return isNaN(num) ? 0 : Math.round(num * 100) / 100;
}

export function parseReceiptText(text: string): Item[] {
  if (!text || !text.trim()) return [];

  const rawLines = text.split('\n');
  const items: Item[] = [];

  for (let i = 0; i < rawLines.length; i++) {
    let line = rawLines[i].trim();
    if (line.length < 3) continue;

    // Clean trailing noise often generated by OCR
    line = line.replace(/[\-_~*+=:;|]+$/, '').trim();
    if (line.length < 3) continue;

    const lower = line.toLowerCase();

    // Check if line contains ignored header/footer keyword
    const isIgnored = IGNORED_WORDS.some(word => {
      const regex = new RegExp(`\\b${word}\\b`, 'i');
      return regex.test(lower);
    });

    if (isIgnored) continue;

    // Look for prices: numbers usually at the end of the line
    // e.g. "2 Empanada Carne 3.600,00" or "Bife de Chorizo $ 18500" or "Pizza Muzzarella 14500.-"
    const priceMatch = line.match(/(?:[$sS§]\s*)?([0-9]{1,3}(?:[.,][0-9]{3})*(?:[.,][0-9]{1,2})?|[0-9]{3,7}(?:[.,][0-9]{1,2})?)(?:\s*[\-_.*])?\s*$/);

    if (!priceMatch) continue;

    const rawPrice = priceMatch[1];
    const fullPriceNum = parsePriceNumber(rawPrice);

    if (fullPriceNum <= 0) continue;

    // Remove price from line
    let restOfLine = line.slice(0, priceMatch.index).trim();
    // Clean up trailing dots, dashes, pipes often present in receipts
    restOfLine = restOfLine.replace(/[\.\-_+=:;|~]+$/, '').trim();

    if (!restOfLine || restOfLine.length < 2) continue;

    // Extract quantity if present at start (e.g. "2 EMPANADA", "1x COCA COLA", "3 - AGUA")
    let qty = 1;
    let name = restOfLine;

    const qtyMatch = restOfLine.match(/^([0-9]{1,2})\s*(?:[xX*]|[-–])?\s+(.+)$/);
    if (qtyMatch) {
      const parsedQty = parseInt(qtyMatch[1], 10);
      if (parsedQty > 0 && parsedQty <= 99) {
        qty = parsedQty;
        name = qtyMatch[2].trim();
      }
    } else {
      // Check quantity at end of description e.g. "EMPANADA CARNE x 3"
      const qtySuffixMatch = restOfLine.match(/^(.+?)\s+[xX*]\s*([0-9]{1,2})$/);
      if (qtySuffixMatch) {
        const parsedQty = parseInt(qtySuffixMatch[2], 10);
        if (parsedQty > 0 && parsedQty <= 99) {
          qty = parsedQty;
          name = qtySuffixMatch[1].trim();
        }
      } else {
        // Check lone trailing quantity column before price e.g. "FLAN CASERO   1"
        const qtyTrailingMatch = restOfLine.match(/^(.+?)\s+([1-9][0-9]?)$/);
        if (qtyTrailingMatch && qtyTrailingMatch[1].length >= 3) {
          const parsedQty = parseInt(qtyTrailingMatch[2], 10);
          if (parsedQty > 0 && parsedQty <= 99) {
            qty = parsedQty;
            name = qtyTrailingMatch[1].trim();
          }
        }
      }
    }

    // Clean up name
    name = name
      .replace(/^[^a-zA-Z0-9áéíóúÁÉÍÓÚñÑ]+/, '')
      .replace(/[^a-zA-Z0-9áéíóúÁÉÍÓÚñÑ%()]+$/, '')
      .trim();

    if (name.length < 2) continue;

    // Calculate unit price: if quantity > 1, check if fullPriceNum is total or unit price
    let unitPrice = fullPriceNum;
    if (qty > 1) {
      unitPrice = Math.round((fullPriceNum / qty) * 100) / 100;
    }

    // Guess mode: beverages and wine often shared, food portions units
    const isBeverage = /(vino|cerveza|gaseosa|coca|agua|jarra|champagne|fernet|aperol|trago|botella)/i.test(name);
    const mode = isBeverage ? 'shared' : 'units';

    items.push({
      id: Date.now() + i * 10,
      name,
      price: unitPrice,
      qty,
      mode,
      shares: {}
    });
  }

  return items;
}
